service: aws-workshop
frameworkVersion: '>=2.35.0'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 3
  logRetentionInDays: 14
  deploymentPrefix: aws-workshop-serverless
  stackTags:
    Description: AWS-Workshop

plugins:
  - workshopUsers

package:
  patterns:
    - src/**
    - '!.npmignore'
    - '!.serverless_plugins'
    - '!README.md'

functions:
  checkTask:
    handler: src/checkTask.hadnler

# you can add CloudFormation resource templates here
resources:
  Resources:
    Colleagues:
      Type: AWS::IAM::Group
      Properties:
        GroupName: "AwsWorkshopParticipants"
        Path: "/aws-workshop/"

    Colleague:
      Type: AWS::IAM::User
      Metadata:
        "Serverless::Plugin::WorkshopUsers": "duplicate-with-user-and-password"
      Properties:
        Groups:
          - !Ref Colleagues
        LoginProfile:
          Password: "W1LL_be_OVERWRITTEN" # See workshopUsers.js
        Path: "/aws-workshop/"
        UserName: "example@example.com" # See workshopUsers.js
