service: aws-workshop
frameworkVersion: '>=2.35.0'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 3
  logRetentionInDays: 14
  deploymentPrefix: aws-workshop-serverless
  stackTags:
    Description: AWS-Workshop

package:
  patterns:
    - src/**
    - '!.npmignore'
    - '!README.md'

functions:
  checkTask:
    handler: src/checkTask.hadnler

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
