service: aws-workshop
frameworkVersion: '>=2.35.0'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 3
  logRetentionInDays: 14
  deploymentPrefix: aws-workshop-serverless
  stackTags:
    Description: AWS-Workshop

plugins:
  - workshopUsers

package:
  patterns:
    - src/**
    - '!config/**'
    - '!.npmignore'
    - '!.serverless_plugins'
    - '!README.md'

functions:
  checkTask:
    role: CheckTaskRole
    handler: src/checkTask.hadnler
    environment:
      SCORES_S3_NAME: !Ref ScoresBucket

resources:
  Resources:
    # Student (Frontend) specific resources
    Ec2ConnectPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: WorkShopStudentUI
        Groups:
          - !Ref Colleagues
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource:
                - !GetAtt CheckTaskLambdaFunction.Arn
            - Effect: Allow
              Action:
                - "s3:ListBucket"
              Resource:
                - !GetAtt ScoresBucket.Arn
                - !Sub "arn:aws:s3:::${ScoresBucket}/*"

    Colleagues:
      Type: AWS::IAM::Group
      Properties:
        GroupName: "AwsWorkshopParticipants"
        Path: "/aws-workshop/"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/ReadOnlyAccess

    Colleague:
      Type: AWS::IAM::User
      Metadata:
        "Serverless::Plugin::WorkshopUsers": "duplicate-with-user-and-password"
      Properties:
        Groups:
          - !Ref Colleagues
        LoginProfile:
          Password: "W1LL_be_OVERWRITTEN" # See workshopUsers.js
        Path: "/aws-workshop/"
        UserName: "example@example.com" # See workshopUsers.js

    # Deployment of the Frontend application
    AwsWorkshop:
      Type: AWS::S3::Bucket
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    AwsWorkshopPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket: !Ref AwsWorkshop
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AwsWorkshop
                  - '/*'
              Principal: '*'

    # Lambda specific resources
    CheckTaskRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: "/aws-workshop/"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: Scores
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                      - "s3:PutObject"
                      - "s3:PutObjectAcl"
                      - "s3:GetObject"
                      - "s3:GetObjectAcl"
                  Resource:
                    - !GetAtt ScoresBucket.Arn
                    - !Sub "arn:aws:s3:::${ScoresBucket}/*"

    ScoresBucket:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration: # Fro Browser API
          CorsRules:
            - AllowedHeaders:
                - "*"
              ExposedHeaders:
                - "x-amz-meta-last-modified"
              AllowedMethods:
                - "GET"
                - "PUT"
                - "POST"
              AllowedOrigins:
                - "*"
              MaxAge: "3000"

    #
    # Resources for the tasks
    #

    # Networking
    Vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        Tags:
          - Key: Name
            Value: VirtualNetwork

    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: Internet Gateway

    VpcToInternetGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: Vpc
        InternetGatewayId:
          Ref: InternetGateway

    # Public subnet 1 (with routes, NAT and IGW)
    PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.0.0/18
        VpcId:
          Ref: Vpc
        MapPublicIpOnLaunch: true
        Tags:
          - Key: Name
            Value: PublicSubnet 1

    PublicSubnet1RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: Vpc
        Tags:
          - Key: Name
            Value: PublicSubnet1 RouteTable

    PublicSubnet1RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: PublicSubnet1RouteTable
        SubnetId:
          Ref: PublicSubnet1

    PublicSubnet1DefaultRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PublicSubnet1RouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGateway
      DependsOn:
        - Vpc

    PublicSubnet1NatIp:
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc
        Tags:
          - Key: Name
            Value: NatGatewey1 IP

    NatGateway1:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId:
          Fn::GetAtt:
            - PublicSubnet1NatIp
            - AllocationId
        SubnetId:
          Ref: PublicSubnet1
        Tags:
          - Key: Name
            Value: Nat Gateway

    # Public subnet 1 (with routes, NAT and IGW)
    PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.64.0/18
        VpcId:
          Ref: Vpc
        MapPublicIpOnLaunch: true
        Tags:
          - Key: Name
            Value: PublicSubnet2

    PublicSubnet2RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: Vpc
        Tags:
          - Key: Name
            Value: PublicSubnet2 RouteTable

    PublicSubnet2RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: PublicSubnet2RouteTable
        SubnetId:
          Ref: PublicSubnet2

    PublicSubnet2RouteTableDefaultRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PublicSubnet2RouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGateway
      DependsOn:
        - Vpc

    PublicSubnet2NatIp:
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc
        Tags:
          - Key: Name
            Value: NatGatewey2 IP

    NatGateway2:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId:
          Fn::GetAtt:
            - PublicSubnet2NatIp
            - AllocationId
        SubnetId:
          Ref: PublicSubnet2
        Tags:
          - Key: Name
            Value: NatGateway

    # Private subnet 1 (with routes to NAT gateway)
    PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.128.0/18
        VpcId:
          Ref: Vpc
        MapPublicIpOnLaunch: false
        Tags:
          - Key: Name
            Value: PrivateSubnet1

    PrivateSubnet1RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: Vpc
        Tags:
          - Key: Name
            Value: PrivateSubnet1 RouteTable

    PrivateSubnet1RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: PrivateSubnet1RouteTable
        SubnetId:
          Ref: PrivateSubnet1

    PrivateSubnet1DefaultRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PrivateSubnet1RouteTable
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway1

    # Private subnet 2 (with routes to NAT gateway)
    PrivateSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.192.0/18
        VpcId:
          Ref: Vpc
        MapPublicIpOnLaunch: false
        Tags:
          - Key: Name
            Value: PrivateSubnet2

    PrivateSubnet2RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: Vpc
        Tags:
          - Key: Name
            Value: PrivateSubnet2 RouteTable

    PrivateSubnet2RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: PrivateSubnet2RouteTable
        SubnetId:
          Ref: PrivateSubnet2

    PrivateSubnet2DefaultRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PrivateSubnet2RouteTable
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway2

  Outputs:
    AccountId:
      Description: AWS Account number, where all tasks should be executed on
      Value: !Ref "AWS::AccountId"
    CheckTaskLambdaFunctionName:
      Description: Name to be used when invoking via SDK
      Value: !Ref CheckTaskLambdaFunction
    ScoresBucketName:
      Description: Name of the bucket, where shores will be stored (and read from by UI)
      Value: !Ref ScoresBucket
    AwsWorkshopBucketName:
      Description: Entry point bucket name (where all Frontend assets will be deployed)
      Value: !Ref AwsWorkshop
    AwsWorkshopSecureUrl:
      Value: !Sub "https://${AwsWorkshop.DomainName}/index.html"